Version: 1

Database:
  # -------------------------------------------------------------------------------------------------
  # Prefix utilisé avant les messages dans la console liés à la base de données.
  # -------------------------------------------------------------------------------------------------
  Prefix: '§7[§bDatabase§7]§b'

  # -------------------------------------------------------------------------------------------------
  # L'URL de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Url: jdbc:mysql://panel.arkamc.fr:3306/s24_OmegaLobby

  # -------------------------------------------------------------------------------------------------
  # Utilisateur de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Username: u24_6mEKcJRDIe

  # -------------------------------------------------------------------------------------------------
  # Password de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Password: "ig1TI28nKMyAIdLN6.O^cpOe"