Version: 1

Server_Name: "Lobby"

Jedis:
  # -------------------------------------------------------------------------------------------------
  # Prefix utilisé avant les messages dans la console liés à la base de données Jedis.
  # -------------------------------------------------------------------------------------------------
  Prefix: '§7[§bJedis§7]§b'

  Bungee_Ip: 51.210.155.175
  Bungee_Port: 6379
  Bungee_Password: "DFNLCPMXXHODAYVYDYBDRFQRIBKHOKTD"

