Version: 1

Server_Name: "Lobby"

Database:
  # -------------------------------------------------------------------------------------------------
  # Prefix utilisé avant les messages dans la console liés à la base de données.
  # -------------------------------------------------------------------------------------------------
  Prefix: '§7[§bDatabase§7]§b'

  # -------------------------------------------------------------------------------------------------
  # L'URL de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Url: jdbc:mysql://panel.arkamc.fr:3306/s24_OmegaLobby

  # -------------------------------------------------------------------------------------------------
  # Utilisateur de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Username: u24_6mEKcJRDIe

  # -------------------------------------------------------------------------------------------------
  # Password de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Password: "ig1TI28nKMyAIdLN6.O^cpOe"

Jedis:
  # -------------------------------------------------------------------------------------------------
  # Prefix utilisé avant les messages dans la console liés à la base de données Jedis.
  # -------------------------------------------------------------------------------------------------
  Prefix: '§7[§bJedis§7]§b'

  Bungee_Ip: 51.210.155.175
  Bungee_Port: 6379
  Bungee_Password: "DFNLCPMXXHODAYVYDYBDRFQRIBKHOKTD"

