Version: 1

Server_Name: "server_name"

Database:
  # -------------------------------------------------------------------------------------------------
  # Prefix utilisé avant les messages dans la console liés à la base de données.
  # -------------------------------------------------------------------------------------------------
  Prefix: '§7[§bDatabase§7]§b'

  # -------------------------------------------------------------------------------------------------
  # L'URL de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Url: "url"

  # -------------------------------------------------------------------------------------------------
  # Utilisateur de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Username: "username"

  # -------------------------------------------------------------------------------------------------
  # Password de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Password: "password"

Jedis:
  # -------------------------------------------------------------------------------------------------
  # Prefix utilisé avant les messages dans la console liés à la base de données Redis.
  # -------------------------------------------------------------------------------------------------
  Prefix: '§cJedis - §9'

  # -------------------------------------------------------------------------------------------------
  # L'ip de connection à la base de donnée Redis
  # -------------------------------------------------------------------------------------------------
  Bungee_Ip: "ip"

  # -------------------------------------------------------------------------------------------------
  # Le port de connection à la base de donnée Redis
  # -------------------------------------------------------------------------------------------------
  Bungee_Port: 6379

  # -------------------------------------------------------------------------------------------------
  # Le password de connection à la base de donnée Redis
  # -------------------------------------------------------------------------------------------------
  Bungee_Password: "password"

