Version: 1

Server_Name: "server_name"

Database:
  # -------------------------------------------------------------------------------------------------
  # Prefix utilisé avant les messages dans la console liés à la base de données.
  # -------------------------------------------------------------------------------------------------
  Prefix: '§7[§bDatabase§7]§b'

  # -------------------------------------------------------------------------------------------------
  # L'URL de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Url: "url"

  # -------------------------------------------------------------------------------------------------
  # Utilisateur de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Username: "username"

  # -------------------------------------------------------------------------------------------------
  # Password de connection à la base de donnée
  # -------------------------------------------------------------------------------------------------
  Password: "password"

Jedis:
  # -------------------------------------------------------------------------------------------------
  # Prefix utilisé avant les messages dans la console liés à la base de données Redis.
  # -------------------------------------------------------------------------------------------------
  Prefix: '§cJedis - §9'

  # -------------------------------------------------------------------------------------------------
  # L'ip de connection à la base de donnée Redis
  # -------------------------------------------------------------------------------------------------
  Bungee_Ip: "ip"

  # -------------------------------------------------------------------------------------------------
  # Le port de connection à la base de donnée Redis
  # -------------------------------------------------------------------------------------------------
  Bungee_Port: 6379

  # -------------------------------------------------------------------------------------------------
  # Le password de connection à la base de donnée Redis
  # -------------------------------------------------------------------------------------------------
  Bungee_Password: "password"

Scoreboard:
  # Example:
  # - UniqueId: 'exemple_scoreboard'
  #   display_condition: ''
  #   if-condition-not-met: 'main_scoreboard'
  #   title: ''§6§l%server_name% network'
  #   updateTime: 20
  #   content:
  #     - "§7"
  #     - "§7Joueurs: §b%online_players%"
  #   default: true
  #
  - UniqueId: 'main_scoreboard'
    # La condition d'affichage du scoreboard, si vide le display_condition ainsi
    # que l'if-condition-not-met ne seront pas pris en compte.
    display_condition: ''
    # Le scoreboard à afficher si la condition n'est pas remplie
    if-condition-not-met: 'main_scoreboard'
    # Le titre du scoreboard
    title: '&6&l%server_name% network'
    # Le temps d'update du scoreboard
    update_interval: 20
    # Le contenu du scoreboard
    contents:
      - "&7"
      - "&7Joueurs: &b%online_players%"
    # Si le scoreboard est par défaut
    default: true


